// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPI5gjhRclIWmSVdFShgTB4Iy3IdZKyg',
    appId: '1:1079142193800:web:1e1c904ca2a9622145dd3d',
    messagingSenderId: '1079142193800',
    projectId: 'loans-1e3d0',
    authDomain: 'loans-1e3d0.firebaseapp.com',
    storageBucket: 'loans-1e3d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQinX3d_UfoV9wvSxfw6K5wAMJIdskNDc',
    appId: '1:1079142193800:android:e38d4b02de1d807445dd3d',
    messagingSenderId: '1079142193800',
    projectId: 'loans-1e3d0',
    storageBucket: 'loans-1e3d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBTt3BKu_8JStAbgo1TCL1rNEEJqGXac',
    appId: '1:1079142193800:ios:d4aafa9701e7975d45dd3d',
    messagingSenderId: '1079142193800',
    projectId: 'loans-1e3d0',
    storageBucket: 'loans-1e3d0.firebasestorage.app',
    iosBundleId: 'com.example.businessCalculation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBTt3BKu_8JStAbgo1TCL1rNEEJqGXac',
    appId: '1:1079142193800:ios:d4aafa9701e7975d45dd3d',
    messagingSenderId: '1079142193800',
    projectId: 'loans-1e3d0',
    storageBucket: 'loans-1e3d0.firebasestorage.app',
    iosBundleId: 'com.example.businessCalculation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGPI5gjhRclIWmSVdFShgTB4Iy3IdZKyg',
    appId: '1:1079142193800:web:c5a6673933b5e4cb45dd3d',
    messagingSenderId: '1079142193800',
    projectId: 'loans-1e3d0',
    authDomain: 'loans-1e3d0.firebaseapp.com',
    storageBucket: 'loans-1e3d0.firebasestorage.app',
  );
}
